// frontend-react/src/components/Home.tsx
export default function Home() {
  return (
    <>
      {/* hero */}
      <section className="hero">
        <div className="container text-center">
          <div className="row justify-content-center">
            <div className="col-lg-8">
              <i className="bi bi-book-half icon-large"></i>
              <h1 className="fw-bold mb-3">Sistema de Gestión de Biblioteca</h1>
              <p className="lead mb-4">
                Proyecto Full‑Stack con arquitectura MEAN. Gestiona tu catálogo de libros de
                forma profesional con operaciones CRUD completas, filtros avanzados y más.
              </p>
              <div className="d-flex justify-content-center gap-3 flex-wrap">
                <a href="/libros" className="btn btn-light btn-lg btn-hero shadow">
                  <i className="bi bi-journals me-2"></i>Ver Catálogo
                </a>
                <a href="/libros/nuevo" className="btn btn-outline-light btn-lg btn-hero">
                  <i className="bi bi-plus-circle me-2"></i>Agregar Libro
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* características */}
      <section className="feature-section">
        <div className="container">
          <div className="row g-4 mb-5">
            <div className="col-md-4">
              <div className="feature-card h-100">
                <div className="card-body text-center p-4">
                  <div
                    className="feature-icon"
                    style={{ background: 'linear-gradient(135deg, #3498DB, #2980B9)' }}
                  >
                    <i className="bi bi-database-fill"></i>
                  </div>
                  <h5 className="card-title fw-bold mb-3">Base de Datos MongoDB</h5>
                  <p className="card-text text-muted">
                    25+ libros en catálogo con información completa. Sistema CRUD con
                    validaciones y reglas de negocio implementadas.
                  </p>
                </div>
              </div>
            </div>
            <div className="col-md-4">
              <div className="feature-card h-100">
                <div className="card-body text-center p-4">
                  <div
                    className="feature-icon"
                    style={{ background: 'linear-gradient(135deg, #27AE60, #229954)' }}
                  >
                    <i className="bi bi-funnel-fill"></i>
                  </div>
                  <h5 className="card-title fw-bold mb-3">Filtros Avanzados</h5>
                  <p className="card-text text-muted">
                    Busca por título, autor o género. Filtra por disponibilidad. Combina múltiples
                    criterios con paginación integrada.
                  </p>
                </div>
              </div>
            </div>
            <div className="col-md-4">
              <div className="feature-card h-100">
                <div className="card-body text-center p-4">
                  <div
                    className="feature-icon"
                    style={{ background: 'linear-gradient(135deg, #E74C3C, #C0392B)' }}
                  >
                    <i className="bi bi-pencil-square"></i>
                  </div>
                  <h5 className="card-title fw-bold mb-3">Operaciones CRUD</h5>
                  <p className="card-text text-muted">
                    Crea, edita, visualiza y elimina libros en tiempo real. Formularios con
                    validaciones completas y mensajes claros.
                  </p>
                </div>
              </div>
            </div>
          </div>

          <div className="row justify-content-center mb-5">
            <div className="col-lg-10">
              <div className="card border-0" style={{
                background: 'linear-gradient(135deg, #ECF0F1 0%, #BDC3C7 100%)',
                borderRadius: '15px'
              }}>
                <div className="card-body p-4">
                  <h5 className="text-center mb-4 fw-bold" style={{ color: '#2C3E50' }}>
                    <i className="bi bi-stack me-2"></i>Stack Tecnológico
                  </h5>
                  <div className="row text-center g-3">
                    <div className="col-6 col-md-3">
                      <div className="p-3">
                        <i className="bi bi-server" style={{ fontSize: '2.5rem', color: '#27AE60' }}></i>
                        <p className="mt-2 mb-0 fw-bold small">Node.js</p>
                      </div>
                    </div>
                    <div className="col-6 col-md-3">
                      <div className="p-3">
                        <i className="bi bi-broadcast" style={{ fontSize: '2.5rem', color: '#3498DB' }}></i>
                        <p className="mt-2 mb-0 fw-bold small">Express</p>
                      </div>
                    </div>
                    <div className="col-6 col-md-3">
                      <div className="p-3">
                        <i className="bi bi-database" style={{ fontSize: '2.5rem', color: '#27AE60' }}></i>
                        <p className="mt-2 mb-0 fw-bold small">MongoDB</p>
                      </div>
                    </div>
                    <div className="col-6 col-md-3">
                      <div className="p-3">
                        <i className="bi bi-bootstrap-fill" style={{ fontSize: '2.5rem', color: '#7952B3' }}></i>
                        <p className="mt-2 mb-0 fw-bold small">React + Angular</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="row g-4 text-center mb-5">
            <div className="col-md-3 col-6">
              <div className="p-3">
                <h2 className="display-4 fw-bold text-primary">25+</h2>
                <p className="text-muted mb-0">Libros en Catálogo</p>
              </div>
            </div>
            <div className="col-md-3 col-6">
              <div className="p-3">
                <h2 className="display-4 fw-bold text-success">20</h2>
                <p className="text-muted mb-0">Géneros Literarios</p>
              </div>
            </div>
            <div className="col-md-3 col-6">
              <div className="p-3">
                <h2 className="display-4 fw-bold text-danger">6</h2>
                <p className="text-muted mb-0">Reglas de Negocio</p>
              </div>
            </div>
            <div className="col-md-3 col-6">
              <div className="p-3">
                <h2 className="display-4 fw-bold text-warning">100%</h2>
                <p className="text-muted mb-0">CRUD Funcional</p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}

// frontend-angular/src/app/components/home/home.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent {

}


<!-- HERO SECTION -->
<section class="hero-section">
  <div class="container text-center">
    <div class="hero-content">
      <h1 class="hero-title">
        <i class="bi bi-book"></i>
        BiblioHub
      </h1>
      <p class="hero-subtitle">
        Tu catálogo de libros reinventado
      </p>
      <div class="hero-buttons mt-4">
        <a class="btn btn-primary btn-lg me-3" routerLink="/libros">
          <i class="bi bi-journal-text"></i> Explorar Catálogo
        </a>
        <a class="btn btn-success btn-lg" routerLink="/nuevo">
          <i class="bi bi-plus-circle"></i> Nuevo Libro
        </a>
      </div>
    </div>
  </div>
</section>

<!-- KPIs SECTION -->
<section class="kpis-section">
  <div class="container">
    <div class="section-header text-center mb-5">
      <h2>Estadísticas del Catálogo</h2>
      <p class="text-muted">Datos actualizados sobre tus libros</p>
    </div>

    <div *ngIf="loading" class="spinner-container">
      <div class="spinner-border text-primary" role="status">
        <span class="visually-hidden">Cargando...</span>
      </div>
    </div>

    <div *ngIf="!loading" class="row g-4">
      <!-- KPI: Total Libros -->
      <div class="col-md-6 col-lg-3">
        <div class="kpi-card">
          <div class="kpi-icon">
            <i class="bi bi-book"></i>
          </div>
          <div class="kpi-content">
            <h3 class="kpi-number">{{ totalLibros }}</h3>
            <p class="kpi-label">Libros Totales</p>
          </div>
        </div>
      </div>

      <!-- KPI: Disponibles -->
      <div class="col-md-6 col-lg-3">
        <div class="kpi-card">
          <div class="kpi-icon available">
            <i class="bi bi-check-circle"></i>
          </div>
          <div class="kpi-content">
            <h3 class="kpi-number">{{ librosDisponibles }}</h3>
            <p class="kpi-label">Disponibles</p>
          </div>
        </div>
      </div>

      <!-- KPI: Géneros -->
      <div class="col-md-6 col-lg-3">
        <div class="kpi-card">
          <div class="kpi-icon genres">
            <i class="bi bi-tags"></i>
          </div>
          <div class="kpi-content">
            <h3 class="kpi-number">{{ generosUnicos.size }}</h3>
            <p class="kpi-label">Géneros</p>
          </div>
        </div>
      </div>

      <!-- KPI: Último Agregado -->
      <div class="col-md-6 col-lg-3">
        <div class="kpi-card">
          <div class="kpi-icon recent">
            <i class="bi bi-star"></i>
          </div>
          <div class="kpi-content">
            <h3 class="kpi-number" *ngIf="ultimoLibro" style="font-size: 0.95rem; line-height: 1.2;">
              {{ ultimoLibro.titulo | slice:0:15 }}{{ ultimoLibro.titulo.length > 15 ? '...' : '' }}
            </h3>
            <p class="kpi-label" *ngIf="ultimoLibro">Último agregado</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- EXPLORE BY GENRES -->
<section class="genres-section">
  <div class="container">
    <div class="section-header text-center mb-4">
      <h2>Explorar por Géneros</h2>
    </div>

    <div class="d-flex flex-wrap justify-content-center gap-2 mb-5" *ngIf="!loading && generosArray.length">
      <a *ngFor="let g of generosArray" class="badge badge-lg bg-info text-decoration-none" href="javascript:void(0)">
        {{ g }}
      </a>
    </div>

    <div class="text-center text-muted" *ngIf="!loading && generosArray.length === 0">
      <p>No hay géneros disponibles aún.</p>
    </div>

    <div class="text-center" *ngIf="loading">
      <div class="spinner-border text-primary" role="status">
        <span class="visually-hidden">Cargando...</span>
      </div>
    </div>
  </div>
</section>

<!-- HOW IT WORKS SECTION -->
<section class="how-it-works-section">
  <div class="container">
    <div class="section-header text-center mb-5">
      <h2>Cómo Funciona</h2>
      <p class="text-muted">Tres simples pasos para gestionar tu catálogo</p>
    </div>

    <div class="row g-4">
      <!-- Step 1 -->
      <div class="col-md-4">
        <div class="step-card">
          <div class="step-number">1</div>
          <div class="step-icon">
            <i class="bi bi-plus-square"></i>
          </div>
          <h4 class="step-title">Agrega Libros</h4>
          <p class="step-description">
            Crea nuevos títulos con toda la información: ISBN, autor, editorial, géneros, descripción 
            y más detalles.
          </p>
        </div>
      </div>

      <!-- Step 2 -->
      <div class="col-md-4">
        <div class="step-card">
          <div class="step-number">2</div>
          <div class="step-icon">
            <i class="bi bi-search"></i>
          </div>
          <h4 class="step-title">Busca y Filtra</h4>
          <p class="step-description">
            Encuentra libros rápidamente por título, autor, género o disponibilidad. Filtros 
            potentes para navegar tu colección.
          </p>
        </div>
      </div>

      <!-- Step 3 -->
      <div class="col-md-4">
        <div class="step-card">
          <div class="step-number">3</div>
          <div class="step-icon">
            <i class="bi bi-pencil-square"></i>
          </div>
          <h4 class="step-title">Edita y Controla</h4>
          <p class="step-description">
            Actualiza información, gestiona stock, controla disponibilidad y elimina libros cuando 
            sea necesario.
          </p>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- FEATURES HIGHLIGHT SECTION -->
<section class="features-section">
  <div class="container">
    <div class="row align-items-center g-5">
      <div class="col-lg-6">
        <h2>Características Principales</h2>
        <ul class="features-list">
          <li>
            <i class="bi bi-check-circle-fill"></i>
            <span><strong>CRUD Completo</strong> - Crear, leer, actualizar y eliminar libros</span>
          </li>
          <li>
            <i class="bi bi-check-circle-fill"></i>
            <span><strong>Validaciones</strong> - Formularios reactivos con validación en tiempo real</span>
          </li>
          <li>
            <i class="bi bi-check-circle-fill"></i>
            <span><strong>Búsqueda Avanzada</strong> - Filtros por título, autor, género y más</span>
          </li>
          <li>
            <i class="bi bi-check-circle-fill"></i>
            <span><strong>Paginación</strong> - Navega entre páginas de resultados</span>
          </li>
          <li>
            <i class="bi bi-check-circle-fill"></i>
            <span><strong>Gestión de Stock</strong> - Controla disponibilidad y cantidad</span>
          </li>
          <li>
            <i class="bi bi-check-circle-fill"></i>
            <span><strong>Interfaz Moderna</strong> - Diseño premium y totalmente responsive</span>
          </li>
        </ul>
      </div>

      <div class="col-lg-6">
        <div class="tech-stack">
          <div class="tech-item">
            <i class="bi bi-bootstrap-fill"></i>
            <div>
              <h5>Frontend Moderno</h5>
              <p>Angular 18+ con TypeScript y Bootstrap 5</p>
            </div>
          </div>
          <div class="tech-item">
            <i class="bi bi-server"></i>
            <div>
              <h5>Backend Robusto</h5>
              <p>Node.js + Express + MongoDB</p>
            </div>
          </div>
          <div class="tech-item">
            <i class="bi bi-database"></i>
            <div>
              <h5>Base de Datos</h5>
              <p>MongoDB con índices optimizados</p>
            </div>
          </div>
          <div class="tech-item">
            <i class="bi bi-cloud-upload"></i>
            <div>
              <h5>Deploy Escalable</h5>
              <p>Listo para Vercel y plataformas cloud</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- CALL TO ACTION SECTION -->
<section class="cta-section">
  <div class="container">
    <div class="cta-content text-center">
      <h2>¿Listo para comenzar?</h2>
      <p>Explora tu catálogo o agrega nuevos títulos ahora</p>
      <div class="cta-buttons mt-4">
        <a class="btn btn-primary btn-lg me-3" routerLink="/libros">
          <i class="bi bi-journal-text"></i> Ver Catálogo Completo
        </a>
        <a class="btn btn-success btn-lg" routerLink="/nuevo">
          <i class="bi bi-plus-circle"></i> Crear Nuevo Libro
        </a>
      </div>
    </div>
  </div>
</section>
