// frontend-angular/src/app/components/libro-form/libro-form.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators, FormArray } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { LibroService } from '../../services/libro.service';

@Component({
  selector: 'app-libro-form',
  templateUrl: './libro-form.component.html',
  styleUrls: ['./libro-form.component.css']
})
export class LibroFormComponent implements OnInit {
  libroForm: FormGroup;
  isEditMode: boolean = false;
  libroId: string | null = null;
  loading: boolean = false;
  error: string = '';
  successMessage: string = '';

  generosDisponibles: string[] = [
    'Ficción', 'No Ficción', 'Ciencia', 'Historia',
    'Tecnología', 'Arte', 'Biografía', 'Educación'
  ];

  idiomasDisponibles: string[] = [
    'español', 'inglés', 'francés', 'alemán', 'italiano', 'portugués'
  ];

  constructor(
    private fb: FormBuilder,
    private libroService: LibroService,
    private router: Router,
    private route: ActivatedRoute
  ) {
    this.libroForm = this.fb.group({
      isbn: ['', [
        Validators.required,
        Validators.pattern(/^\d{10}(\d{3})?$/)
      ]],
      titulo: ['', [
        Validators.required,
        Validators.minLength(2),
        Validators.maxLength(200)
      ]],
      autor: ['', [
        Validators.required,
        Validators.minLength(2),
        Validators.maxLength(100)
      ]],
      editorial: ['', [
        Validators.required,
        Validators.minLength(2)
      ]],
      anioPublicacion: ['', [
        Validators.required,
        Validators.min(1000),
        Validators.max(new Date().getFullYear())
      ]],
      generos: this.fb.array([], Validators.required),
      numeroPaginas: ['', [
        Validators.required,
        Validators.min(1)
      ]],
      descripcion: ['', [
        Validators.required,
        Validators.minLength(10),
        Validators.maxLength(2000)
      ]],
      idioma: ['español', Validators.required],
      precio: ['', [
        Validators.required,
        Validators.min(0)
      ]],
      stock: ['', [
        Validators.required,
        Validators.min(0)
      ]],
      portada: ['', Validators.pattern(/^https?:\/\/.+/)]
    });
  }

  ngOnInit(): void {
    this.libroId = this.route.snapshot.paramMap.get('id');
    if (this.libroId) {
      this.isEditMode = true;
      this.loadLibro(this.libroId);
    }
  }

  get generosFormArray(): FormArray {
    return this.libroForm.get('generos') as FormArray;
  }

  onGeneroChange(event: any, genero: string): void {
    if (event.target.checked) {
      this.generosFormArray.push(this.fb.control(genero));
    } else {
      const index = this.generosFormArray.controls.findIndex(x => x.value === genero);
      this.generosFormArray.removeAt(index);
    }
  }

  isGeneroSelected(genero: string): boolean {
    return this.generosFormArray.value.includes(genero);
  }

  loadLibro(id: string): void {
    this.loading = true;
    this.libroService.getLibroById(id).subscribe({
      next: (response) => {
        const libro = response.data;
        this.libroForm.patchValue({
          isbn: libro.isbn,
          titulo: libro.titulo,
          autor: libro.autor,
          editorial: libro.editorial,
          anioPublicacion: libro.anioPublicacion,
          numeroPaginas: libro.numeroPaginas,
          descripcion: libro.descripcion,
          idioma: libro.idioma,
          precio: libro.precio,
          stock: libro.stock,
          portada: libro.portada || ''
        });

        // Cargar géneros
        this.generosFormArray.clear();
        libro.generos.forEach(genero => {
          this.generosFormArray.push(this.fb.control(genero));
        });

        this.loading = false;
      },
      error: (err) => {
        this.error = 'Error al cargar el libro.';
        this.loading = false;
        console.error('Error:', err);
      }
    });
  }

  onSubmit(): void {
    if (this.libroForm.invalid) {
      Object.keys(this.libroForm.controls).forEach(key => {
        this.libroForm.get(key)?.markAsTouched();
      });
      return;
    }

    this.loading = true;
    this.error = '';
    this.successMessage = '';

    const formData = this.libroForm.value;

    if (this.isEditMode && this.libroId) {
      this.libroService.updateLibro(this.libroId, formData).subscribe({
        next: (response) => {
          this.successMessage = 'Libro actualizado correctamente.';
          this.loading = false;
          setTimeout(() => {
            this.router.navigate(['/libro', this.libroId]);
          }, 1500);
        },
        error: (err) => {
          this.error = err.error?.message || 'Error al actualizar el libro.';
          this.loading = false;
          console.error('Error:', err);
        }
      });
    } else {
      this.libroService.createLibro(formData).subscribe({
        next: (response) => {
          this.successMessage = 'Libro creado correctamente.';
          this.loading = false;
          setTimeout(() => {
            this.router.navigate(['/libros']);
          }, 1500);
        },
        error: (err) => {
          this.error = err.error?.message || 'Error al crear el libro.';
          this.loading = false;
          console.error('Error:', err);
        }
      });
    }
  }

  getErrorMessage(field: string): string {
    const control = this.libroForm.get(field);
    if (control?.hasError('required')) {
      return 'Este campo es obligatorio.';
    }
    if (control?.hasError('minlength')) {
      return `Mínimo ${control.errors?.['minlength'].requiredLength} caracteres.`;
    }
    if (control?.hasError('maxlength')) {
      return `Máximo ${control.errors?.['maxlength'].requiredLength} caracteres.`;
    }
    if (control?.hasError('min')) {
      return `El valor mínimo es ${control.errors?.['min'].min}.`;
    }
    if (control?.hasError('max')) {
      return `El valor máximo es ${control.errors?.['max'].max}.`;
    }
    if (control?.hasError('pattern')) {
      if (field === 'isbn') {
        return 'ISBN debe tener 10 o 13 dígitos.';
      }
      if (field === 'portada') {
        return 'Debe ser una URL válida (http:// o https://).';
      }
    }
    return '';
  }

  cancelar(): void {
    this.router.navigate(['/libros']);
  }
}


<div class="container mt-4">
  <h2 class="mb-4">
    <i class="bi" [ngClass]="isEditMode ? 'bi-pencil-square' : 'bi-plus-circle'"></i>
    {{ isEditMode ? 'Editar Libro' : 'Agregar Nuevo Libro' }}
  </h2>

  <!-- Mensajes -->
  <div class="alert alert-success" *ngIf="successMessage">
    <i class="bi bi-check-circle"></i> {{ successMessage }}
  </div>

  <div class="alert alert-danger" *ngIf="error">
    <i class="bi bi-exclamation-triangle"></i> {{ error }}
  </div>

  <!-- Formulario -->
  <div class="card shadow">
    <div class="card-body">
      <form [formGroup]="libroForm" (ngSubmit)="onSubmit()">

        <!-- Información Básica -->
        <h5 class="text-primary mb-3">
          <i class="bi bi-info-circle"></i> Información Básica
        </h5>

        <div class="row">
          <div class="col-md-6 mb-3">
            <label class="form-label">ISBN <span class="text-danger">*</span></label>
            <input
              type="text"
              class="form-control"
              formControlName="isbn"
              placeholder="Ej: 9788420412146"
              [class.is-invalid]="libroForm.get('isbn')?.invalid && libroForm.get('isbn')?.touched"
              [class.is-valid]="libroForm.get('isbn')?.valid && libroForm.get('isbn')?.touched">
            <div class="invalid-feedback" *ngIf="libroForm.get('isbn')?.invalid && libroForm.get('isbn')?.touched">
              {{ getErrorMessage('isbn') }}
            </div>
          </div>

          <div class="col-md-6 mb-3">
            <label class="form-label">Título <span class="text-danger">*</span></label>
            <input
              type="text"
              class="form-control"
              formControlName="titulo"
              placeholder="Ej: Don Quijote de la Mancha"
              [class.is-invalid]="libroForm.get('titulo')?.invalid && libroForm.get('titulo')?.touched"
              [class.is-valid]="libroForm.get('titulo')?.valid && libroForm.get('titulo')?.touched">
            <div class="invalid-feedback" *ngIf="libroForm.get('titulo')?.invalid && libroForm.get('titulo')?.touched">
              {{ getErrorMessage('titulo') }}
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6 mb-3">
            <label class="form-label">Autor <span class="text-danger">*</span></label>
            <input
              type="text"
              class="form-control"
              formControlName="autor"
              placeholder="Ej: Miguel de Cervantes"
              [class.is-invalid]="libroForm.get('autor')?.invalid && libroForm.get('autor')?.touched"
              [class.is-valid]="libroForm.get('autor')?.valid && libroForm.get('autor')?.touched">
            <div class="invalid-feedback" *ngIf="libroForm.get('autor')?.invalid && libroForm.get('autor')?.touched">
              {{ getErrorMessage('autor') }}
            </div>
          </div>

          <div class="col-md-6 mb-3">
            <label class="form-label">Editorial <span class="text-danger">*</span></label>
            <input
              type="text"
              class="form-control"
              formControlName="editorial"
              placeholder="Ej: Editorial Planeta"
              [class.is-invalid]="libroForm.get('editorial')?.invalid && libroForm.get('editorial')?.touched"
              [class.is-valid]="libroForm.get('editorial')?.valid && libroForm.get('editorial')?.touched">
            <div class="invalid-feedback" *ngIf="libroForm.get('editorial')?.invalid && libroForm.get('editorial')?.touched">
              {{ getErrorMessage('editorial') }}
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-4 mb-3">
            <label class="form-label">Año de Publicación <span class="text-danger">*</span></label>
            <input
              type="number"
              class="form-control"
              formControlName="anioPublicacion"
              placeholder="Ej: 2023"
              [class.is-invalid]="libroForm.get('anioPublicacion')?.invalid && libroForm.get('anioPublicacion')?.touched"
              [class.is-valid]="libroForm.get('anioPublicacion')?.valid && libroForm.get('anioPublicacion')?.touched">
            <div class="invalid-feedback" *ngIf="libroForm.get('anioPublicacion')?.invalid && libroForm.get('anioPublicacion')?.touched">
              {{ getErrorMessage('anioPublicacion') }}
            </div>
          </div>

          <div class="col-md-4 mb-3">
            <label class="form-label">Número de Páginas <span class="text-danger">*</span></label>
            <input
              type="number"
              class="form-control"
              formControlName="numeroPaginas"
              placeholder="Ej: 350"
              [class.is-invalid]="libroForm.get('numeroPaginas')?.invalid && libroForm.get('numeroPaginas')?.touched"
              [class.is-valid]="libroForm.get('numeroPaginas')?.valid && libroForm.get('numeroPaginas')?.touched">
            <div class="invalid-feedback" *ngIf="libroForm.get('numeroPaginas')?.invalid && libroForm.get('numeroPaginas')?.touched">
              {{ getErrorMessage('numeroPaginas') }}
            </div>
          </div>

          <div class="col-md-4 mb-3">
            <label class="form-label">Idioma <span class="text-danger">*</span></label>
            <select
              class="form-select"
              formControlName="idioma"
              [class.is-invalid]="libroForm.get('idioma')?.invalid && libroForm.get('idioma')?.touched"
              [class.is-valid]="libroForm.get('idioma')?.valid && libroForm.get('idioma')?.touched">
              <option *ngFor="let idioma of idiomasDisponibles" [value]="idioma">
                {{ idioma | titlecase }}
              </option>
            </select>
          </div>
        </div>

        <!-- Géneros -->
        <h5 class="text-primary mb-3 mt-4">
          <i class="bi bi-tags"></i> Géneros <span class="text-danger">*</span>
        </h5>
        <div class="row mb-3">
          <div class="col-md-3" *ngFor="let genero of generosDisponibles">
            <div class="form-check">
              <input
                class="form-check-input"
                type="checkbox"
                [id]="genero"
                [checked]="isGeneroSelected(genero)"
                (change)="onGeneroChange($event, genero)">
              <label class="form-check-label" [for]="genero">
                {{ genero }}
              </label>
            </div>
          </div>
        </div>
        <div class="text-danger small" *ngIf="generosFormArray.invalid && generosFormArray.touched">
          Selecciona al menos un género.
        </div>

        <!-- Descripción -->
        <div class="mb-3 mt-4">
          <label class="form-label">Descripción <span class="text-danger">*</span></label>
          <textarea
            class="form-control"
            formControlName="descripcion"
            rows="4"
            placeholder="Descripción del libro..."
            [class.is-invalid]="libroForm.get('descripcion')?.invalid && libroForm.get('descripcion')?.touched"
            [class.is-valid]="libroForm.get('descripcion')?.valid && libroForm.get('descripcion')?.touched"></textarea>
          <div class="invalid-feedback" *ngIf="libroForm.get('descripcion')?.invalid && libroForm.get('descripcion')?.touched">
            {{ getErrorMessage('descripcion') }}
          </div>
        </div>

        <!-- Precio y Stock -->
        <h5 class="text-primary mb-3 mt-4">
          <i class="bi bi-cash-coin"></i> Precio y Disponibilidad
        </h5>
        <div class="row">
          <div class="col-md-6 mb-3">
            <label class="form-label">Precio (€) <span class="text-danger">*</span></label>
            <input
              type="number"
              step="0.01"
              class="form-control"
              formControlName="precio"
              placeholder="Ej: 19.99"
              [class.is-invalid]="libroForm.get('precio')?.invalid && libroForm.get('precio')?.touched"
              [class.is-valid]="libroForm.get('precio')?.valid && libroForm.get('precio')?.touched">
            <div class="invalid-feedback" *ngIf="libroForm.get('precio')?.invalid && libroForm.get('precio')?.touched">
              {{ getErrorMessage('precio') }}
            </div>
          </div>

          <div class="col-md-6 mb-3">
            <label class="form-label">Stock <span class="text-danger">*</span></label>
            <input
              type="number"
              class="form-control"
              formControlName="stock"
              placeholder="Ej: 50"
              [class.is-invalid]="libroForm.get('stock')?.invalid && libroForm.get('stock')?.touched"
              [class.is-valid]="libroForm.get('stock')?.valid && libroForm.get('stock')?.touched">
            <div class="invalid-feedback" *ngIf="libroForm.get('stock')?.invalid && libroForm.get('stock')?.touched">
              {{ getErrorMessage('stock') }}
            </div>
          </div>
        </div>

        <!-- Portada (Opcional) -->
        <div class="mb-3">
          <label class="form-label">URL de la Portada (Opcional)</label>
          <input
            type="text"
            class="form-control"
            formControlName="portada"
            placeholder="https://ejemplo.com/imagen.jpg"
            [class.is-invalid]="libroForm.get('portada')?.invalid && libroForm.get('portada')?.touched"
            [class.is-valid]="libroForm.get('portada')?.valid && libroForm.get('portada')?.touched">
          <div class="invalid-feedback" *ngIf="libroForm.get('portada')?.invalid && libroForm.get('portada')?.touched">
            {{ getErrorMessage('portada') }}
          </div>
        </div>

        <!-- Botones -->
        <div class="d-flex justify-content-end gap-2 mt-4">
          <button type="button" class="btn btn-secondary" (click)="cancelar()" [disabled]="loading">
            <i class="bi bi-x-circle"></i> Cancelar
          </button>
          <button type="submit" class="btn btn-primary" [disabled]="loading || libroForm.invalid">
            <span *ngIf="loading" class="spinner-border spinner-border-sm me-2"></span>
            <i *ngIf="!loading" class="bi" [ngClass]="isEditMode ? 'bi-save' : 'bi-plus-circle'"></i>
            {{ isEditMode ? 'Actualizar' : 'Crear' }} Libro
          </button>
        </div>
      </form>
    </div>
  </div>

  <div class="alert alert-info mt-3">
    <i class="bi bi-info-circle"></i> Los campos marcados con <span class="text-danger">*</span> son obligatorios.
  </div>
</div>

// frontend-react/src/components/LibroForm.tsx
import { useState, useEffect } from 'react'
import type { FormEvent } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import Loader from './common/Loader'
import ErrorAlert from './common/ErrorAlert'
import libroService from '../services/libroService'
import type { LibroCreate } from '../services/libroService'

export default function LibroForm() {
  const navigate = useNavigate()
  const { id } = useParams<{ id: string }>()
  const isEditMode = !!id

  // Estados del formulario
  const [formData, setFormData] = useState<LibroCreate>({
    isbn: '',
    titulo: '',
    autor: '',
    editorial: '',
    anioPublicacion: new Date().getFullYear(),
    generos: [],
    numeroPaginas: 1,
    descripcion: '',
    idioma: 'español',
    precio: 0,
    stock: 1,
    portada: ''
  })

  const [errors, setErrors] = useState<Record<string, string>>({})
  const [loading, setLoading] = useState(false)
  const [loadingData, setLoadingData] = useState(false)
  const [submitError, setSubmitError] = useState<string | null>(null)

  // Géneros disponibles
  const generosDisponibles = [
    'ficción', 'no ficción', 'novela', 'ciencia ficción', 'fantasía',
    'thriller', 'misterio', 'romance', 'histórico', 'biografía',
    'autoayuda', 'tecnología', 'ciencia', 'poesía', 'drama',
    'terror', 'aventura', 'policial', 'filosofía', 'ensayo'
  ]

  const idiomasDisponibles = ['español', 'inglés', 'francés', 'alemán', 'portugués', 'italiano', 'otro']

  // Cargar libro si estamos en modo edición
  useEffect(() => {
    if (isEditMode && id) {
      loadLibro(id)
    }
  }, [id, isEditMode])

  async function loadLibro(libroId: string) {
    setLoadingData(true)
    try {
      const response = await libroService.getLibroById(libroId)
      const libro = response.data
      setFormData({
        isbn: libro.isbn,
        titulo: libro.titulo,
        autor: libro.autor,
        editorial: libro.editorial,
        anioPublicacion: libro.anioPublicacion,
        generos: libro.generos,
        numeroPaginas: libro.numeroPaginas,
        descripcion: libro.descripcion,
        idioma: libro.idioma,
        precio: libro.precio,
        stock: libro.stock,
        portada: libro.portada || ''
      })
    } catch (err: any) {
      setSubmitError(err?.message || 'Error al cargar el libro')
    } finally {
      setLoadingData(false)
    }
  }

  // Validar formulario
  function validateForm(): boolean {
    const newErrors: Record<string, string> = {}

    // ISBN
    const isbnClean = formData.isbn.replace(/-/g, '')
    if (!formData.isbn) {
      newErrors.isbn = 'El ISBN es requerido'
    } else if (!/^(\d{10}|\d{13})$/.test(isbnClean)) {
      newErrors.isbn = 'El ISBN debe tener 10 o 13 dígitos'
    }

    // Título
    if (!formData.titulo.trim()) {
      newErrors.titulo = 'El título es requerido'
    } else if (formData.titulo.length < 2) {
      newErrors.titulo = 'El título debe tener al menos 2 caracteres'
    }

    // Autor
    if (!formData.autor.trim()) {
      newErrors.autor = 'El autor es requerido'
    } else if (formData.autor.length < 2) {
      newErrors.autor = 'El autor debe tener al menos 2 caracteres'
    }

    // Editorial
    if (!formData.editorial.trim()) {
      newErrors.editorial = 'La editorial es requerida'
    }

    // Año
    if (formData.anioPublicacion < 1000 || formData.anioPublicacion > 2026) {
      newErrors.anioPublicacion = 'El año debe estar entre 1000 y 2026'
    }

    // Géneros
    if (formData.generos.length === 0) {
      newErrors.generos = 'Debe seleccionar al menos un género'
    } else if (formData.generos.length > 3) {
      newErrors.generos = 'Máximo 3 géneros permitidos'
    }

    // Páginas
    if (formData.numeroPaginas < 1 || formData.numeroPaginas > 10000) {
      newErrors.numeroPaginas = 'Las páginas deben estar entre 1 y 10000'
    }

    // Descripción
    if (!formData.descripcion.trim()) {
      newErrors.descripcion = 'La descripción es requerida'
    } else if (formData.descripcion.length > 2000) {
      newErrors.descripcion = 'La descripción no puede exceder 2000 caracteres'
    }

    // Precio
    if (formData.precio < 0 || formData.precio > 10000) {
      newErrors.precio = 'El precio debe estar entre 0 y 10000'
    }

    // Stock
    if (formData.stock < 0) {
      newErrors.stock = 'El stock no puede ser negativo'
    }

    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  // Manejar cambios en inputs
  function handleChange(field: keyof LibroCreate, value: any) {
    setFormData((prev) => ({ ...prev, [field]: value }))
    // Limpiar error del campo
    if (errors[field]) {
      setErrors((prev) => {
        const newErrors = { ...prev }
        delete newErrors[field]
        return newErrors
      })
    }
  }

  // Manejar selección de géneros
  function handleGeneroToggle(genero: string) {
    const currentGeneros = formData.generos
    if (currentGeneros.includes(genero)) {
      handleChange('generos', currentGeneros.filter((g) => g !== genero))
    } else {
      if (currentGeneros.length < 3) {
        handleChange('generos', [...currentGeneros, genero])
      }
    }
  }

  // Enviar formulario
  async function handleSubmit(e: FormEvent) {
    e.preventDefault()

    if (!validateForm()) {
      return
    }

    setLoading(true)
    setSubmitError(null)

    try {
      // Preparar datos para enviar - eliminar portada si está vacía
      const dataToSend = { ...formData }
      if (!dataToSend.portada || dataToSend.portada.trim() === '') {
        delete dataToSend.portada
      }

      console.log('Datos a enviar:', dataToSend)

      if (isEditMode && id) {
        await libroService.updateLibro(id, dataToSend)
      } else {
        await libroService.createLibro(dataToSend)
      }
      navigate('/libros')
    } catch (err: any) {
      console.error('Error completo:', err)
      setSubmitError(err?.message || 'Error al guardar el libro')
    } finally {
      setLoading(false)
    }
  }

  if (loadingData) {
    return <Loader text="Cargando datos del libro..." />
  }

  return (
    <div className="container py-4 form-container">
      <div className="row justify-content-center">
        <div className="col-lg-8">
          <div className="card shadow">
            <div className="card-header">
              <h3 className="mb-0">
                {isEditMode ? '✏️ Editar Libro' : '➕ Agregar Nuevo Libro'}
              </h3>
            </div>
            <div className="card-body">
              {submitError && (
                <ErrorAlert message={submitError} onDismiss={() => setSubmitError(null)} />
              )}

              <form onSubmit={handleSubmit}>
                {/* ISBN */}
                <div className="mb-3">
                  <label className="form-label">ISBN *</label>
                  <input
                    type="text"
                    className={`form-control ${errors.isbn ? 'is-invalid' : ''}`}
                    value={formData.isbn}
                    onChange={(e) => handleChange('isbn', e.target.value)}
                    placeholder="Ej: 9788408043640"
                  />
                  {errors.isbn && <div className="invalid-feedback">{errors.isbn}</div>}
                  <div className="form-text">ISBN-10 (10 dígitos) o ISBN-13 (13 dígitos)</div>
                </div>

                {/* Título */}
                <div className="mb-3">
                  <label className="form-label">Título *</label>
                  <input
                    type="text"
                    className={`form-control ${errors.titulo ? 'is-invalid' : ''}`}
                    value={formData.titulo}
                    onChange={(e) => handleChange('titulo', e.target.value)}
                    placeholder="Ej: Cien años de soledad"
                  />
                  {errors.titulo && <div className="invalid-feedback">{errors.titulo}</div>}
                </div>

                {/* Autor */}
                <div className="mb-3">
                  <label className="form-label">Autor *</label>
                  <input
                    type="text"
                    className={`form-control ${errors.autor ? 'is-invalid' : ''}`}
                    value={formData.autor}
                    onChange={(e) => handleChange('autor', e.target.value)}
                    placeholder="Ej: Gabriel García Márquez"
                  />
                  {errors.autor && <div className="invalid-feedback">{errors.autor}</div>}
                </div>

                {/* Editorial */}
                <div className="mb-3">
                  <label className="form-label">Editorial *</label>
                  <input
                    type="text"
                    className={`form-control ${errors.editorial ? 'is-invalid' : ''}`}
                    value={formData.editorial}
                    onChange={(e) => handleChange('editorial', e.target.value)}
                    placeholder="Ej: Editorial Sudamericana"
                  />
                  {errors.editorial && <div className="invalid-feedback">{errors.editorial}</div>}
                </div>

                <div className="row">
                  {/* Año */}
                  <div className="col-md-4 mb-3">
                    <label className="form-label">Año de Publicación *</label>
                    <input
                      type="number"
                      className={`form-control ${errors.anioPublicacion ? 'is-invalid' : ''}`}
                      value={formData.anioPublicacion}
                      onChange={(e) => handleChange('anioPublicacion', parseInt(e.target.value))}
                      min="1000"
                      max="2026"
                    />
                    {errors.anioPublicacion && <div className="invalid-feedback">{errors.anioPublicacion}</div>}
                  </div>

                  {/* Páginas */}
                  <div className="col-md-4 mb-3">
                    <label className="form-label">Número de Páginas *</label>
                    <input
                      type="number"
                      className={`form-control ${errors.numeroPaginas ? 'is-invalid' : ''}`}
                      value={formData.numeroPaginas}
                      onChange={(e) => handleChange('numeroPaginas', parseInt(e.target.value))}
                      min="1"
                      max="10000"
                    />
                    {errors.numeroPaginas && <div className="invalid-feedback">{errors.numeroPaginas}</div>}
                  </div>

                  {/* Idioma */}
                  <div className="col-md-4 mb-3">
                    <label className="form-label">Idioma *</label>
                    <select
                      className="form-select"
                      value={formData.idioma}
                      onChange={(e) => handleChange('idioma', e.target.value)}
                    >
                      {idiomasDisponibles.map((idioma) => (
                        <option key={idioma} value={idioma}>
                          {idioma.charAt(0).toUpperCase() + idioma.slice(1)}
                        </option>
                      ))}
                    </select>
                  </div>
                </div>

                {/* Géneros */}
                <div className="mb-3">
                  <label className="form-label">Géneros * (Máximo 3)</label>
                  <div className="border rounded p-3 generos-list">
                    <div className="row g-2">
                      {generosDisponibles.map((genero) => (
                        <div key={genero} className="col-md-4">
                          <div className="form-check">
                            <input
                              className="form-check-input"
                              type="checkbox"
                              id={`genero-${genero}`}
                              checked={formData.generos.includes(genero)}
                              onChange={() => handleGeneroToggle(genero)}
                              disabled={!formData.generos.includes(genero) && formData.generos.length >= 3}
                            />
                            <label className="form-check-label" htmlFor={`genero-${genero}`}>
                              {genero.charAt(0).toUpperCase() + genero.slice(1)}
                            </label>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                  {errors.generos && <div className="text-danger small mt-1">{errors.generos}</div>}
                  <div className="form-text">
                    Seleccionados: {formData.generos.length}/3
                  </div>
                </div>

                {/* Descripción */}
                <div className="mb-3">
                  <label className="form-label">Descripción *</label>
                  <textarea
                    className={`form-control ${errors.descripcion ? 'is-invalid' : ''}`}
                    value={formData.descripcion}
                    onChange={(e) => handleChange('descripcion', e.target.value)}
                    rows={4}
                    placeholder="Escribe una breve descripción del libro..."
                    maxLength={2000}
                  />
                  {errors.descripcion && <div className="invalid-feedback">{errors.descripcion}</div>}
                  <div className="form-text">
                    {formData.descripcion.length}/2000 caracteres
                  </div>
                </div>

                <div className="row">
                  {/* Precio */}
                  <div className="col-md-6 mb-3">
                    <label className="form-label">Precio (€) *</label>
                    <input
                      type="number"
                      step="0.01"
                      className={`form-control ${errors.precio ? 'is-invalid' : ''}`}
                      value={formData.precio}
                      onChange={(e) => handleChange('precio', parseFloat(e.target.value))}
                      min="0"
                      max="10000"
                    />
                    {errors.precio && <div className="invalid-feedback">{errors.precio}</div>}
                  </div>

                  {/* Stock */}
                  <div className="col-md-6 mb-3">
                    <label className="form-label">Stock *</label>
                    <input
                      type="number"
                      className={`form-control ${errors.stock ? 'is-invalid' : ''}`}
                      value={formData.stock}
                      onChange={(e) => handleChange('stock', parseInt(e.target.value))}
                      min="0"
                    />
                    {errors.stock && <div className="invalid-feedback">{errors.stock}</div>}
                  </div>
                </div>

                {/* Portada */}
                <div className="mb-3">
                  <label className="form-label">URL de Portada (opcional)</label>
                  <input
                    type="url"
                    className="form-control"
                    value={formData.portada}
                    onChange={(e) => handleChange('portada', e.target.value)}
                    placeholder="https://ejemplo.com/portada.jpg"
                  />
                  <div className="form-text">Ingresa la URL de una imagen</div>
                </div>

                {/* Botones */}
                <div className="d-flex gap-2">
                  <button
                    type="submit"
                    className="btn btn-primary"
                    disabled={loading}
                  >
                    {loading ? (
                      <>
                        <span className="spinner-border spinner-border-sm me-2" role="status" aria-hidden="true"></span>
                        Guardando...
                      </>
                    ) : (
                      <>{isEditMode ? 'Guardar Cambios' : 'Crear Libro'}</>
                    )}
                  </button>
                  <button
                    type="button"
                    className="btn btn-secondary"
                    onClick={() => navigate('/libros')}
                    disabled={loading}
                  >
                    Cancelar
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
