// frontend-angular/src/app/components/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [RouterLink, RouterLinkActive],
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent {

}


<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <a class="navbar-brand d-flex align-items-center" routerLink="/">
      <i class="bi bi-book"></i>
      <span class="ms-2">BiblioHub</span>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <form class="d-flex ms-auto me-3" role="search">
        <input class="form-control me-2 search-input" type="search" placeholder="Buscar libros..." aria-label="Search">
        <!-- opcionalmente un botón de búsqueda icon -->
      </form>
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}">
            <i class="bi bi-house-door"></i> Inicio
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLink="/libros" routerLinkActive="active">
            <i class="bi bi-journal-text"></i> Catálogo
          </a>
        </li>
        <li class="nav-item">
          <a class="btn btn-success btn-sm" routerLink="/nuevo">
            <i class="bi bi-plus-circle"></i> Nuevo Libro
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

// frontend-react/src/components/Navbar.tsx
// Componente de barra de navegación profesional

type NavbarProps = {
  isDarkMode: boolean
  onToggleTheme: () => void
}

export default function Navbar(_props: NavbarProps) {
  return (
    <nav className="navbar navbar-expand-lg navbar-dark navbar-custom sticky-top shadow-lg">
      <div className="container-fluid px-4">
        {/* Logo/Brand */}
        <a className="navbar-brand fw-bold d-flex align-items-center" href="/">
          <i className="bi bi-book-fill me-2" style={{ fontSize: '1.5rem' }}></i>
          <span>Biblioteca MEAN</span>
        </a>

        {/* Botón toggle para móvil */}
        <button
          className="navbar-toggler border-0"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
        >
          <span className="navbar-toggler-icon"></span>
        </button>

        {/* Items de navegación */}
        <div className="collapse navbar-collapse" id="navbarNav">
          <ul className="navbar-nav ms-auto align-items-center">
            <li className="nav-item">
              <a className="nav-link px-3" href="/">
                <i className="bi bi-house-fill me-1"></i>
                Inicio
              </a>
            </li>
            <li className="nav-item">
              <a className="nav-link px-3" href="/libros">
                <i className="bi bi-journals me-1"></i>
                Catálogo
              </a>
            </li>

            {/* Separador vertical */}
            <li className="nav-item d-none d-lg-block mx-2">
              <div style={{
                width: '1px',
                height: '25px',
                background: 'rgba(255,255,255,0.3)'
              }}></div>
            </li>

            {/* Botón de tema - removido temporalmente para mantener estética consistente */}
            {/*
            <li className="nav-item">
              <button
                className="btn btn-sm btn-outline-light rounded-circle d-flex align-items-center justify-content-center"
                onClick={onToggleTheme}
                aria-label={`Cambiar a modo ${isDarkMode ? 'claro' : 'oscuro'}`}
                title={`Cambiar a modo ${isDarkMode ? 'claro' : 'oscuro'}`}
                style={{
                  width: '40px',
                  height: '40px',
                  transition: 'all 0.3s ease'
                }}
              >
                <i className={`bi ${isDarkMode ? 'bi-sun-fill' : 'bi-moon-fill'}`}></i>
              </button>
            </li>
            */}
          </ul>
        </div>
      </div>
    </nav>
  )
}
