// frontend-react/src/components/LibroDetalle.tsx
import { useEffect, useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import libroService from '../services/libroService'
import type { Libro } from '../services/libroService'

export default function LibroDetalle() {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()

  const [libro, setLibro] = useState<Libro | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [deleting, setDeleting] = useState(false)

  useEffect(() => {
    if (id) {
      loadLibro(id)
    }
  }, [id])

  async function loadLibro(libroId: string) {
    setLoading(true)
    setError(null)

    try {
      const response = await libroService.getLibroById(libroId)
      setLibro(response.data)
    } catch (err: any) {
      setError(err?.message || 'Error al cargar el libro')
    } finally {
      setLoading(false)
    }
  }

  async function handleDelete() {
    if (!libro || !window.confirm(`¿Estás seguro de eliminar "${libro.titulo}"?`)) {
      return
    }

    setDeleting(true)
    try {
      await libroService.deleteLibro(libro._id)
      navigate('/libros')
    } catch (err: any) {
      setError(err?.message || 'Error al eliminar el libro')
      setDeleting(false)
    }
  }

  if (loading) {
    return (
      <div className="container py-5 text-center">
        <div className="spinner-border text-primary" style={{ width: '3rem', height: '3rem' }} role="status">
          <span className="visually-hidden">Cargando...</span>
        </div>
        <p className="mt-3">Cargando información del libro...</p>
      </div>
    )
  }

  if (error || !libro) {
    return (
      <div className="container py-5">
        <div className="alert alert-danger">
          <h4 className="alert-heading">Error</h4>
          <p>{error || 'Libro no encontrado'}</p>
          <hr />
          <button className="btn btn-primary" onClick={() => navigate('/libros')}>
            Volver al catálogo
          </button>
        </div>
      </div>
    )
  }

  return (
    <div className="container py-4">
      {/* Botones superiores */}
      <div className="mb-4 d-flex justify-content-between align-items-center">
        <button className="btn btn-secondary" onClick={() => navigate('/libros')}>
          ← Volver al Catálogo
        </button>
        <div className="d-flex gap-2">
          <button
            className="btn btn-warning"
            onClick={() => navigate(`/libros/editar/${libro._id}`)}
          >
            <i className="bi bi-pencil"></i> Editar
          </button>
          <button
            className="btn btn-danger"
            onClick={handleDelete}
            disabled={deleting}
          >
            {deleting ? (
              <>
                <span className="spinner-border spinner-border-sm me-2" />
                Eliminando...
              </>
            ) : (
              <>
                <i className="bi bi-trash"></i> Eliminar
              </>
            )}
          </button>
        </div>
      </div>

      <div className="row">
        {/* Columna de imagen */}
        <div className="col-md-4">
          <div className="card shadow-sm mb-4">
            {libro.portada ? (
              <div style={{
                backgroundColor: '#f8f9fa',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                minHeight: '500px'
              }}>
                <img
                  src={libro.portada}
                  className="card-img-top"
                  alt={`Portada de ${libro.titulo}`}
                  style={{
                    width: '100%',
                    height: 'auto',
                    maxHeight: '600px',
                    objectFit: 'contain'
                  }}
                  onError={(e) => {
                    e.currentTarget.src = 'https://via.placeholder.com/400x600?text=Sin+Portada'
                  }}
                />
              </div>
            ) : (
              <div
                className="card-img-top bg-secondary d-flex align-items-center justify-content-center text-white"
                style={{ height: '500px' }}
              >
                <div className="text-center">
                  <i className="bi bi-book" style={{ fontSize: '5rem' }}></i>
                  <p className="mt-3 mb-0">Sin portada disponible</p>
                </div>
              </div>
            )}
            <div className="card-body text-center">
              {libro.disponible ? (
                <span className="badge bg-success fs-6 w-100">✓ Disponible</span>
              ) : (
                <span className="badge bg-danger fs-6 w-100">✕ No disponible</span>
              )}
            </div>
          </div>
        </div>

        {/* Columna de información */}
        <div className="col-md-8">
          <div className="card shadow-sm">
            <div className="card-header bg-primary text-white">
              <h2 className="mb-0">{libro.titulo}</h2>
            </div>
            <div className="card-body">
              {/* Autor */}
              <div className="mb-3">
                <h5 className="text-muted mb-0">Autor</h5>
                <h4>{libro.autor}</h4>
              </div>

              {/* Géneros */}
              <div className="mb-3">
                <h6 className="text-muted">Géneros</h6>
                <div>
                  {libro.generos.map((genero) => (
                    <span key={genero} className="badge bg-primary me-2 mb-2">
                      {genero}
                    </span>
                  ))}
                </div>
              </div>

              {/* Descripción */}
              <div className="mb-4">
                <h6 className="text-muted">Descripción</h6>
                <p className="lead">{libro.descripcion}</p>
              </div>

              {/* Detalles en tabla */}
              <h6 className="text-muted">Detalles del Libro</h6>
              <table className="table table-bordered">
                <tbody>
                  <tr>
                    <th style={{ width: '30%' }}>ISBN</th>
                    <td>{libro.isbn}</td>
                  </tr>
                  <tr>
                    <th>Editorial</th>
                    <td>{libro.editorial}</td>
                  </tr>
                  <tr>
                    <th>Año de Publicación</th>
                    <td>{libro.anioPublicacion}</td>
                  </tr>
                  <tr>
                    <th>Número de Páginas</th>
                    <td>{libro.numeroPaginas} páginas</td>
                  </tr>
                  <tr>
                    <th>Idioma</th>
                    <td className="text-capitalize">{libro.idioma}</td>
                  </tr>
                  <tr>
                    <th>Precio</th>
                    <td className="fs-5 fw-bold text-success">{libro.precio.toFixed(2)} €</td>
                  </tr>
                  <tr>
                    <th>Stock</th>
                    <td>
                      <span className={`badge ${libro.stock > 0 ? 'bg-success' : 'bg-danger'}`}>
                        {libro.stock} {libro.stock === 1 ? 'unidad' : 'unidades'}
                      </span>
                    </td>
                  </tr>
                  <tr>
                    <th>Disponibilidad</th>
                    <td>
                      {libro.disponible ? (
                        <span className="text-success fw-bold">✓ Disponible para compra</span>
                      ) : (
                        <span className="text-danger fw-bold">✕ No disponible</span>
                      )}
                    </td>
                  </tr>
                </tbody>
              </table>

              {/* Metadatos */}
              <div className="mt-4">
                <h6 className="text-muted">Información del Sistema</h6>
                <table className="table table-sm">
                  <tbody>
                    <tr>
                      <th style={{ width: '30%' }}>ID</th>
                      <td><code>{libro._id}</code></td>
                    </tr>
                    {libro.createdAt && (
                      <tr>
                        <th>Fecha de Creación</th>
                        <td>{new Date(libro.createdAt).toLocaleString('es-ES')}</td>
                      </tr>
                    )}
                    {libro.updatedAt && (
                      <tr>
                        <th>Última Actualización</th>
                        <td>{new Date(libro.updatedAt).toLocaleString('es-ES')}</td>
                      </tr>
                    )}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// frontend-angular/src/app/components/libro-detalle/libro-detalle.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { LibroService } from '../../services/libro.service';
import { Libro } from '../../models/libro.model';

@Component({
  selector: 'app-libro-detalle',
  templateUrl: './libro-detalle.component.html',
  styleUrls: ['./libro-detalle.component.css']
})
export class LibroDetalleComponent implements OnInit {
  libro: Libro | null = null;
  loading: boolean = false;
  error: string = '';

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private libroService: LibroService
  ) { }

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.loadLibro(id);
    }
  }

  loadLibro(id: string): void {
    this.loading = true;
    this.libroService.getLibroById(id).subscribe({
      next: (response) => {
        this.libro = response.data;
        this.loading = false;
      },
      error: (err) => {
        this.error = 'Error al cargar el libro. Por favor, intenta de nuevo.';
        this.loading = false;
        console.error('Error:', err);
      }
    });
  }

  volver(): void {
    this.router.navigate(['/libros']);
  }

  editar(): void {
    if (this.libro) {
      this.router.navigate(['/editar', this.libro._id]);
    }
  }

  eliminar(): void {
    if (this.libro && confirm(`¿Estás seguro de que deseas eliminar "${this.libro.titulo}"?`)) {
      this.libroService.deleteLibro(this.libro._id).subscribe({
        next: () => {
          this.router.navigate(['/libros']);
        },
        error: (err) => {
          this.error = 'Error al eliminar el libro.';
          console.error('Error:', err);
        }
      });
    }
  }
}


<div class="container mt-4">
  <!-- Loading Spinner -->
  <div class="spinner-container" *ngIf="loading">
    <div class="spinner-border text-primary" role="status" style="width: 3rem; height: 3rem;">
      <span class="visually-hidden">Cargando...</span>
    </div>
  </div>

  <!-- Error Message -->
  <div class="alert alert-danger" *ngIf="error">
    <i class="bi bi-exclamation-triangle"></i> {{ error }}
    <button class="btn btn-secondary ms-3" (click)="volver()">Volver al listado</button>
  </div>

  <!-- Detalle del Libro -->
  <div *ngIf="!loading && libro">
    <div class="mb-3">
      <button class="btn btn-secondary" (click)="volver()">
        <i class="bi bi-arrow-left"></i> Volver
      </button>
    </div>

    <div class="card shadow-lg">
      <div class="card-header bg-primary text-white">
        <h3 class="mb-0">
          <i class="bi bi-book"></i> {{ libro.titulo }}
        </h3>
      </div>
      <div class="card-body">
        <div class="row">
          <!-- Imagen del libro -->
          <div class="col-md-4">
            <div class="text-center mb-3">
              <img
                [src]="libro.portada || 'https://via.placeholder.com/300x400?text=Sin+Portada'"
                [alt]="libro.titulo"
                class="img-fluid rounded shadow"
                style="max-height: 400px; object-fit: cover;">
            </div>
            <div class="d-grid gap-2">
              <button class="btn btn-warning" (click)="editar()">
                <i class="bi bi-pencil"></i> Editar
              </button>
              <button class="btn btn-danger" (click)="eliminar()">
                <i class="bi bi-trash"></i> Eliminar
              </button>
            </div>
          </div>

          <!-- Información del libro -->
          <div class="col-md-8">
            <h5 class="text-primary">Información Básica</h5>
            <table class="table table-borderless">
              <tbody>
                <tr>
                  <td><strong><i class="bi bi-upc-scan"></i> ISBN:</strong></td>
                  <td>{{ libro.isbn }}</td>
                </tr>
                <tr>
                  <td><strong><i class="bi bi-person"></i> Autor:</strong></td>
                  <td>{{ libro.autor }}</td>
                </tr>
                <tr>
                  <td><strong><i class="bi bi-building"></i> Editorial:</strong></td>
                  <td>{{ libro.editorial }}</td>
                </tr>
                <tr>
                  <td><strong><i class="bi bi-calendar"></i> Año de Publicación:</strong></td>
                  <td>{{ libro.anioPublicacion }}</td>
                </tr>
                <tr>
                  <td><strong><i class="bi bi-translate"></i> Idioma:</strong></td>
                  <td>{{ libro.idioma }}</td>
                </tr>
                <tr>
                  <td><strong><i class="bi bi-file-text"></i> Páginas:</strong></td>
                  <td>{{ libro.numeroPaginas }}</td>
                </tr>
              </tbody>
            </table>

            <h5 class="text-primary mt-4">Géneros</h5>
            <div class="mb-3">
              <span class="badge bg-info me-2" *ngFor="let genero of libro.generos">
                {{ genero }}
              </span>
            </div>

            <h5 class="text-primary mt-4">Descripción</h5>
            <p class="text-muted">{{ libro.descripcion }}</p>

            <h5 class="text-primary mt-4">Disponibilidad y Precio</h5>
            <table class="table table-borderless">
              <tbody>
                <tr>
                  <td><strong><i class="bi bi-currency-euro"></i> Precio:</strong></td>
                  <td><h4 class="text-success mb-0">{{ libro.precio | currency:'EUR' }}</h4></td>
                </tr>
                <tr>
                  <td><strong><i class="bi bi-box"></i> Stock:</strong></td>
                  <td>
                    <span class="badge" [ngClass]="libro.stock > 0 ? 'bg-success' : 'bg-danger'">
                      {{ libro.stock }} unidades
                    </span>
                  </td>
                </tr>
                <tr>
                  <td><strong><i class="bi bi-check-circle"></i> Estado:</strong></td>
                  <td>
                    <span class="badge" [ngClass]="libro.disponible ? 'bg-success' : 'bg-danger'">
                      {{ libro.disponible ? 'Disponible' : 'No disponible' }}
                    </span>
                  </td>
                </tr>
              </tbody>
            </table>

            <div class="text-muted small mt-4">
              <p class="mb-1">
                <i class="bi bi-calendar-plus"></i> Creado:
                {{ libro.createdAt | date:'dd/MM/yyyy HH:mm' }}
              </p>
              <p class="mb-0" *ngIf="libro.updatedAt">
                <i class="bi bi-calendar-check"></i> Última actualización:
                {{ libro.updatedAt | date:'dd/MM/yyyy HH:mm' }}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
